# Generated by Django 6.0.7 on 2026-08-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogarticlepagetag_blogarticlepage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_posts_tag',
            field=models.CharField(default='', max_length=250, verbose_name='Tag de posts principais'),
        ),
    ]
