# Generated by Django 6.0.7 on 2026-08-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogindexpage_featured_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_link',
            field=models.URLField(blank=True, default='', verbose_name='Link do Card Principal'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_subtitle',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Subtítulo do Card Principal'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Título do Card Principal'),
        ),
    ]
