# Generated by Django 6.0.7 on 2026-08-03 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blogcategory_blogauthor_blogarticlepage_authors_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMenuLink',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_extra', models.CharField(blank=True, default='', max_length=250, verbose_name='Extra URL')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Link Externo')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloglinks', to='wagtailcore.page', verbose_name='Página Interna')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
