# Generated by Django 6.0.7 on 2026-08-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blogauthorpage_blogauthorslistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthorpage',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='blogauthorpage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='blogs.blogauthor', verbose_name='Autor'),
        ),
    ]
