# Generated by Django 6.0.7 on 2026-08-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_blogauthorpage_summary_alter_blogauthorpage_author'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='header_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_images', to='wagtailimages.image', verbose_name='Foto do Cabeçalho'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='header_text',
            field=models.CharField(blank=True, default='', verbose_name='Texto do Cabeçalho'),
        ),
    ]
