# Generated by Django 6.0.7 on 2026-08-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_blogindexpage_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogMenuLink',
        ),
    ]
