# Generated by Django 6.0.7 on 2026-08-26 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_delete_blogmenulink'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_extra', models.CharField(blank=True, default='', max_length=250, verbose_name='Extra URL')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Link Externo')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloglinks', to='wagtailcore.page', verbose_name='Página Interna')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogmenulink', verbose_name='Superior')),
            ],
        ),
    ]
