# Generated by Django 6.0.7 on 2026-08-26 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_blogmenulink_site'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmenulink',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
    ]
