# Generated by Django 6.0.7 on 2026-08-26 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_alter_blogmenulink_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmenulink',
            name='label',
            field=models.CharField(default='', max_length=150, verbose_name='Label'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmenulink',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blogmenulink', verbose_name='Superior'),
        ),
    ]
