# Generated by Django 6.0.7 on 2026-07-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_listtagcontentspage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listindexpage',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='listindexpage',
            name='main_title',
            field=models.CharField(default='', max_length=150, verbose_name='Título Principal'),
            preserve_default=False,
        ),
    ]
