# Generated by Django 6.0.7 on 2026-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_listindexpage_logo_listindexpage_main_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='page_extra',
            field=models.CharField(default='', max_length=250, verbose_name='Extra URL'),
            preserve_default=False,
        ),
    ]
