# Generated by Django 6.0.7 on 2026-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_menulink_page_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='page_extra',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Extra URL'),
        ),
    ]
