# Generated by Django 6.0.7 on 2026-07-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_alter_menulink_page_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcontentpage',
            name='display_label',
            field=models.CharField(blank=True, default='', verbose_name='Label de Visualização'),
        ),
    ]
