# Generated by Django 6.0.7 on 2026-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_listcontentpage_display_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcontentpage',
            name='display_label',
            field=models.CharField(blank=True, default='', verbose_name='Status'),
        ),
    ]
